### PR TITLE
Remove guava from eclipse-integration server

### PR DESCRIPTION
**Pull request by martin-fleck-at**
#### What it does

Fixes https://github.com/eclipse-glsp/glsp/issues/1413

#### How to test

- Build on the latest nightly target platform where Guava is no longer included
- Check that session behavior still works as expected

#### Changelog

- [x] This PR should be mentioned in the changelog
- [ ] This PR introduces a breaking change (if yes, provide more details below for the changelog and the migration guide)

### CODE REVIEW

**Review by tortmayr — APPROVED** [review]
LGTM! 👍🏼 Thanks.

**Comment by ivy-lli** [comment]
In one of our test instances I've get now a `ConcurrentModificationException` after updating to the nightly 2.3 eclipse integration:

```
org.eclipse.jetty.websocket.core.exception.WebSocketException: DiagramWebsocketEndpoint CLOSE method error: null
	at org.eclipse.jetty.websocket.javax.common.JavaxWebSocketFrameHandler.notifyOnClose(JavaxWebSocketFrameHandler.java:302)
	at org.eclipse.jetty.websocket.javax.common.JavaxWebSocketFrameHandler.onClose(JavaxWebSocketFrameHandler.java:267)
	at org.eclipse.jetty.websocket.javax.common.JavaxWebSocketFrameHandler.onFrame(JavaxWebSocketFrameHandler.java:255)
	at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession$IncomingAdaptor.onFrame(WebSocketCoreSession.java:705)
	at org.eclipse.jetty.websocket.core.AbstractExtension.nextIncomingFrame(AbstractExtension.java:145)
	at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:236)
	at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.emitFrame(DemandingFlusher.java:145)
	at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension$IncomingFlusher.handle(PerMessageDeflateExtension.java:378)
	at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.process(DemandingFlusher.java:169)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:232)
	at org.eclipse.jetty.util.IteratingCallback.succeeded(IteratingCallback.java:350)
	at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.onFrame(DemandingFlusher.java:104)
	at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension.onFrame(PerMessageDeflateExtension.java:93)
	at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:120)
	at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onFrame(WebSocketCoreSession.java:481)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:262)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:455)
	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:340)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:934)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1078)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1019)
	at org.eclipse.glsp.ide.editor.IdeGLSPClient.disconnect(IdeGLSPClient.java:90)
	at org.eclipse.glsp.ide.editor.DiagramWebsocketEndpoint.onClose(DiagramWebsocketEndpoint.java:55)
	at org.eclipse.jetty.websocket.javax.common.JavaxWebSocketFrameHandler.notifyOnClose(JavaxWebSocketFrameHandler.java:295)
	... 28 more
```

I'm not sure if the change about the disconnect is good. You make a forEach over all keys of the map and inside the forEach you remove key of the map.

**Comment by martin-fleck-at** [comment]
@ivy-lli  Good catch! I'll make a fix for it today.

**Comment by martin-fleck-at** [comment]
@ivy-lli https://github.com/eclipse-glsp/glsp-eclipse-integration/pull/105 was merged, there should be a nightly available soon!

**Comment by ivy-lli** [comment]
Great thanks. I will test it 👍

**Comment by ivy-lli** [comment]
I've updated to the latest nightly, and the error didn't appear again. So I think it is fine 👍 
Thanks a lot for the fast update 🚀

**Pull request merged**
